services:
  - type: web
    name: bookstore-backend
    runtime: java
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/virtual-bookstore-1.0.0.jar
    envVars:
      - key: APP_JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://bookstore-faizaan.vercel.app
